#cloud-config
hostname: ${hostname}
package_update: false

write_files:
  - path: /var/www/html/index.html
    permissions: "0644"
    content: |
      <!doctype html>
      <html><body>
        <h1>Hello from ${hostname}</h1>
        <p>If you refresh and the hostname changes — LB is doing its job.</p>
      </body></html>

runcmd:
  - systemctl restart nginx
  - useradd --no-create-home --shell /bin/false node_exporter || true
  - curl -fL --retry 6 --retry-delay 5 --retry-all-errors --connect-timeout 30 --max-time 600 -o /tmp/ne.tar.gz https://github.com/prometheus/node_exporter/releases/download/v1.11.1/node_exporter-1.11.1.linux-amd64.tar.gz
  - tar xzf /tmp/ne.tar.gz -C /tmp/
  - cp /tmp/node_exporter-1.11.1.linux-amd64/node_exporter /usr/local/bin/
  - chown node_exporter:node_exporter /usr/local/bin/node_exporter
  - |
    cat > /etc/systemd/system/node_exporter.service <<'UNIT'
    [Unit]
    Description=Node Exporter
    After=network.target

    [Service]
    User=node_exporter
    Group=node_exporter
    Type=simple
    ExecStart=/usr/local/bin/node_exporter

    [Install]
    WantedBy=multi-user.target
    UNIT
  - systemctl daemon-reload
  - systemctl enable --now node_exporter
